### PR TITLE
Add support for Justine's lambda.com interpreter

### PR DESCRIPTION
**Pull request by unjordy**
This PR adds support for pulling in the source code for Justine's `lambda.com` interpreter, building it, and using it to run tests and the REPL. Its advantages over `Blc` are that it runs on macOS and supports several debug flags that show the internal state of the Krivine machine as it executes, which comes in handy for exploratory programming with lambda calculus.

### CODE REVIEW

**Comment by woodrush** [comment]
Thanks for your pull request! I'm currently asking Justine if it's OK to get all the source files from justine.lol via wget since it may cause lots of traffic. I'll get back to you when we find a way.

**Comment by unjordy** [comment]
Good call!

**Comment by woodrush** [comment]
Got an approval from Justine for getting the sources via wget. Thanks Justine!

I pulled your branch and ran `test run-blc-lambda` on linux, but examples/lambdacraft.cl ended with a segfault, probably because of the memory limit. The Make recipe tries to specify a larger limit but I suspect that it's not working. Could you check if the test runs for that as well?

Also I just noticed that SBCL on Mac doesn't print a newline at the end of the file which makes `diff` to fail. That's another issue. We should probably strip the newline at the end for all interpreters.

**Comment by unjordy** [comment]
Thanks Justine!

Unfortunately I can't repro either error locally on macOS 12.1, compiling with `Apple clang version 13.1.6 (clang-1316.0.21.2.3)`; `make test-blc-lambda` completes successfully with no segfaults or mismatched diffs. I pushed a change to `blc.h` to patch out `TERMS` like for `Blc.S`, which at least resolves a couple of compile warnings. I should be able to test this branch on NixOS later tonight to see if I can make it segfault there.

With `SBCL 2.2.4.nixos` from `nixpkgs-22.05-darwin (70b6236f3cbc815f2cae8d597418c714cf83d1c8)` on macOS, I didn't run into the newline issue. It's certainly possible nixpkgs has patched this issue to make their own tests work, though I couldn't find anything with a quick look at the package derivation.

**Comment by woodrush** [comment]
Thanks for the thorough testing. As for the newline issue, on my Mac I was using `SBCL 2.1.4`, and on Ubuntu it was `SBCL 2.1.11.debian` so it seems that the minor version change solves the newline issue. 2.1.4 is from 2021-04-28 according to the [release notes](http://www.sbcl.org/all-news.html#2.1.4) so I guess it's better to just update SBCL to solve this issue.

At the moment I tried adding a newline for SBCL outputs and lambda.com worked just fine, so for Mac it seems that everything is cleared.

However on Ubuntu, building lambda.com using the same setup didn't work. Here's what I got on Ubuntu:
```
if [ -f "test/backquote.cl.in" ]; then \                                                                                            
        ( cat ./bin/lambdalisp.blc | ./bin/asc2bin; cat examples/backquote.cl test/backquote.cl.in ) | ./bin/lambda.com -b > out/bac
kquote.cl.blc-lambda-out.tmp; else \                                                                                                
        ( cat ./bin/lambdalisp.blc | ./bin/asc2bin; cat examples/backquote.cl ) | ./bin/lambda.com -b > out/backquote.cl.blc-lambda-
out.tmp; fi                                                                                                                         
                                                                                                                                    
ERROR:  OUT OF HEAP                                                                                                                 
   ip:  51431                                                                                                                       
  end:  95146                                                                                                                       
 term:  [ [ [[0  0] ⊤] 0] 1] [0 2] [[[ [ [[0  0] ⊤] 0] 2] [0 5]] [[1  [3  [[2 [6 1]] [6 0]]]] 0]]  [[0 put] put]                    
        0=0                                                                                                                         
        1=6                                                                                                                         
        2=0                                                                                                                         
        3=[0 0]                                                                                                                     
```
Setting `TERMS` to a 10x larger value on Ubuntu made a segfault even for small programs (arithmetic.cl) so I think the term limit is in fact being set properly. I tried using both `clang` and `cc` but got the same results.
Here are the `clang` and `cc` versions:
```sh
$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ cc --version
cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I also tried getting the pre-built lambda.com from justine.lol but that didn't work either on Ubuntu. My Ubuntu machine has 48GB memory and my Mac has 8GB (it's a rather old machine) so the RAM size itself shouldn't be the issue. I think it's some kind of compilation issue.

Since the main purpose for lambda.com is for running on Macs, I think we could leave it as is at the moment.

Just one last thing before we merge your PR - since the original lambda.com binary runs on multiple OSs, and the one built here is built for Mac only, and the `.com` is named for multiple-OS binaries (an [αcτµαlly pδrταblε εxεcµταblε](https://justine.lol/ape.html)), it may be better to rename `lambda.com` to `lambda` to prevent potential confusion. Could you do a quick patch on the name?

**Comment by woodrush** [comment]
Thanks for your contribution!

**Comment by unjordy** [comment]
Thank you for following up and merging! That's an interesting result for `lambda` on Ubuntu. I may dig into it a bit more at a later date -- I plan on studying the `lambda` implementation as a way to expand my knowledge of Krivine machines and lambda calculus as a whole.

**Comment by woodrush** [comment]
You're welcome! That's exciting. Please feel free to ask any questions if you come across any.

I'm curious about the Ubuntu issue too. I'd be happy if you let me know if you find out something.

**Pull request merged**
